### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by RezaMakvandi** [SaeedDev94/ng-persian-datepicker#47]
./node_modules/ng-persian-datepicker/fesm2015/ng-persian-datepicker.mjs:585:225-231 - Error: export 'filter' (imported as 'filter') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, 
scheduled, throwError, timer, using, zip)

"rxjs": "~6.6.0",
"ng-persian-datepicker": "^4.0.1",
with angular 13

**Comment by Saeed-Pooyanfar** [comment]
@RezaMakvandi You must upgrade `rxjs` to `^7.4`
