### ISSUE TITLE
در ورژن قبلی برای این که دیت پیکر هم عرض اینپوت بشه یک اینپوت به نام uiAutoPosition می گرفتید تو این ورژن حذف شده ؟

### ISSUE THREAD

**Issue by amirheydari9** [SaeedDev94/ng-persian-datepicker#48]

**Comment by Saeed-Pooyanfar** [comment]
Yes
The feature doesn't work as should be and removed in the new version
You can use somethings like https://floating-ui.com/ or https://material.angular.io/cdk/overlay/overview
