### ISSUE TITLE
Cannot set an empty default value for date picker

### ISSUE THREAD

**Issue by zatkhahi** [SaeedDev94/ng-persian-datepicker#58]
When I bind ng-persian-datepicker with a formcontrol, it all ways set today's date as default value. How I prevent this and set null value as default?

`
<ng-persian-datepicker [timeEnable]="false" [uiTodayBtnEnable]="false" [uiHideAfterSelectDate]="true" dateFormat="jYYYY/jMM/jDD">
      <input type="text" class="border" formControlName="birthDate" />
    </ng-persian-datepicker>
`

And in angular form builder:
`
birthDate: [null, [Validators.required]],
`

**Comment by Saeed-Pooyanfar** [comment]
Please read `README.md` :

> Complete config reference:
> 
> | Key                   | Type    | Description                                                                                                          | Example                                         |
> |-----------------------|---------|----------------------------------------------------------------------------------------------------------------------|-------------------------------------------------|
> | dateInitValue         | boolean | if no dateValue provided use today as init value. default: `true`                                                    | true                                            |
