### ISSUE TITLE
Disable selecting some special days (like holidays)

### ISSUE THREAD

**Issue by ghost** [SaeedDev94/ng-persian-datepicker#64]
Hi Saeed
Is it possible to disable selecting some special days (like holidays) in the date picker?
Thanks in advance

**Comment by Saeed-Pooyanfar** [comment]
At this moment with current version `v6.0.5` the answer is NO, you can't !

**Comment by FullStackDeveloperrrr** [comment]
I think it will be great if you add this feature. The ability of coloring holidays is another useful feature that makes your calendar more strong
Anyway, Thank you so much for the quick response

**Comment by FullStackDeveloperrrr** [comment]
That's great, I'll appreciate that.
For holidays I think it's not a big deal! Just colorful all Fridays and for other holidays, provide an attribute in the date picker directive that accepts an array of Date objects and colorful those days! We can define that array statically or use other APIs to get the list of holidays. What do you think?

**Comment by moshtaba** [comment]
I think it's necessary for a datepicker to colorize holidays. if you add this it'll be sooooo appreciated.
