### ISSUE TITLE
input clear date

### ISSUE THREAD

**Issue by mohebbisaeed** [SaeedDev94/ng-persian-datepicker#66]
Thanks for the persianDatePicker component, is there an option to empty the input and its effect on the value of the IActiveDate?

**Comment by Saeed-Pooyanfar** [comment]
@mohebbisaeed you should reset value of `IActiveDate` manually (i can't emit `null` to `(dateOnSelect)` beacuse it's a breaking change) but i will implement this feature in the next version and you can use it like:
```typescript
formControl.setValue(null);
```

**Comment by Saeed-Pooyanfar** [comment]
@mohebbisaeed try version `v6.1.1`
