### ISSUE TITLE
use absolute position instead of css display

### ISSUE THREAD

**Issue by mohammadreza99** [SaeedDev94/ng-persian-datepicker#68]
hi, thanks for your great package,
is it possible to use css `position` property instead of  `display` for display the overlay? When the overlay is opened, the rest of the screen elements are pushed down and the layout is messed up

**Comment by hbsoftco** [comment]
I also have this problem @mohammadreza99

**Comment by Saeed-Pooyanfar** [comment]
Please check https://github.com/Saeed-Pooyanfar/ng-persian-datepicker/blob/master/src/styles.scss
+ New demo
