### ISSUE TITLE
open or close ui

### ISSUE THREAD

**Issue by merajseraji** [SaeedDev94/ng-persian-datepicker#69]
hi saeed 
1- how we can know that the dropdown is open or not?
2- how we can open and close is programmatically?
3- can I ask you to add mask to input base on date format and update it while typing? like ----/--/--_--:-- or ..... 
do you have plan to add this feature?

**Comment by Saeed-Pooyanfar** [comment]
Hi
1- In your component define `isOpen: boolean = false` then pass it to lib selector: `<ng-persian-datepicker [(uiIsVisible)]="isOpen" ...`
2- By changing `isOpen` value
3- Unfortunately no, however you can fork this repo and implement it by yourself

**Comment by merajseraji** [comment]
I'm sorry but [(uiIsVisible)] is not working. it is not two way binding, but the first value that bind to it, is the final value and we can't change it.

**Comment by Saeed-Pooyanfar** [comment]
In angular `[prop]` means `@Input` and `(prop)` means `@Output`
When you write `[(prop)]` it means in the component both `@Input` and `@Output` are exists for `prop`
It should works or if doesn't please provide an example on https://stackblitz.com

**Comment by merajseraji** [comment]
I know what is the input and output :)
see this example: 
[https://stackblitz.com/edit/angular-ivy-vgz3hk?file=src/app/app.component.ts](url)

**Comment by Saeed-Pooyanfar** [comment]
In this case the problem is `[uiHideOnOutsideClick]` which is `true` by default
So you should set `[uiHideOnOutsideClick]` value to `false`
