### ISSUE TITLE
Add an option to disable auto scroll

### ISSUE THREAD

**Issue by gholami-mohammad** [SaeedDev94/ng-persian-datepicker#76]
When timeEnable is true, scrollIntoActiveTime function focuses on time inputs and it interrupts users. Is it possible to add an option to handle auto-focus?

**Comment by Saeed-Pooyanfar** [comment]
@gholami-mohammad Yeah, good idea
I will consider this feature in next release
Thanks for your suggestion

**Comment by SaeedDev94** [comment]
Time scroll removed in `v8.0.0` !!
